onCreate:
  - sudo apt-get update -y
  - sudo gem install rails
  - sudo gem install bundler
  - bundle install

onStart:
  - |
        WS_DOMAIN=`cat /home/ubuntu/runcode/ws-url-domain.txt`
        printf "\nGO TO THIS URL TO VIEW PAGE \033[4;34m https://3000-${WS_DOMAIN}\033[0;30m\n\n"
        rails server
